#!/bin/bash

TOOLDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
BASEADDR="$4"
if [ X"$BASEADDR" = X ]; then
  echo "Need to pass in base address as argument 4!"
  exit 1
fi

RETRIES=10

while [ $RETRIES -gt 0 ]
do
    if [ "$("$TOOLDIR"/dfu-util -l 2>/dev/null | grep 0483:df11)" != "" ]
    then
      "$TOOLDIR"/dfu-util -d "$1:$2",0x0483:0xdf11 -a 0 -s "$BASEADDR:leave" -D "$3"
      echo "OK"
      exit 0
    fi
    echo $RETRIES
    RETRIES=$((RETRIES - 1))
    sleep 1;
done

echo "FAIL"
exit 0
